<?php

/*
	Do not edit this file manually. This copy of global file is overwritten
	by extensions editor.
*/

$installed_extensions = array (
  1 => 
  array (
    'package' => 'rep_client_listing',
    'name' => 'rep_client_listing',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/rep_client_listing',
    'active' => 1,
  ),
  2 => 
  array (
    'name' => 'Annual balance breakdown report',
    'package' => 'rep_annual_balance_breakdown',
    'version' => '2.3.0-1',
    'type' => 'extension',
    'active' => 1,
    'path' => 'modules/rep_annual_balance_breakdown',
  ),
  3 => 
  array (
    'name' => 'Annual expense breakdown report',
    'package' => 'rep_annual_expense_breakdown',
    'version' => '2.3.0-1',
    'type' => 'extension',
    'active' => 1,
    'path' => 'modules/rep_annual_expense_breakdown',
  ),
  4 => 
  array (
    'name' => 'Cash Flow Statement Report',
    'package' => 'rep_cash_flow_statement',
    'version' => '2.3.0-1',
    'type' => 'extension',
    'active' => 1,
    'path' => 'modules/rep_cash_flow_statement',
  ),
  5 => 
  array (
    'package' => 'rep_cash_sales',
    'name' => 'rep_cash_sales',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/rep_cash_sales',
    'active' => 1,
  ),
  6 => 
  array (
    'package' => 'rep_customer_account_statement',
    'name' => 'rep_customer_account_statement',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/rep_customer_account_statement',
    'active' => 1,
  ),
  7 => 
  array (
    'package' => 'rep_disbursement_summary',
    'name' => 'rep_disbursement_summary',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/rep_disbursement_summary',
    'active' => 1,
  ),
  8 => 
  array (
    'package' => 'rep_disbursement_summary_sample',
    'name' => 'rep_disbursement_summary_sample',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/rep_disbursement_summary_sample',
    'active' => false,
  ),
  9 => 
  array (
    'package' => 'rep_royalty_sales',
    'name' => 'rep_royalty_sales',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/rep_royalty_sales',
    'active' => 1,
  ),
  10 => 
  array (
    'package' => 'rep_sales_remittance',
    'name' => 'rep_sales_remittance',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/rep_sales_remittance',
    'active' => 1,
  ),
  11 => 
  array (
    'package' => 'rep_sales_status',
    'name' => 'rep_sales_status',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/rep_sales_status',
    'active' => 1,
  ),
  12 => 
  array (
    'package' => 'rep_series_report',
    'name' => 'rep_series_report',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/rep_series_report',
    'active' => 1,
  ),
  13 => 
  array (
    'package' => 'payroll',
    'name' => 'payroll',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/payroll',
    'active' => 1,
  ),
  14 => 
  array (
    'name' => 'Company Dashboard',
    'package' => 'dashboard',
    'version' => '2.3.15-5',
    'type' => 'extension',
    'active' => 1,
    'path' => 'modules/dashboard',
  ),
  15 => 
  array (
    'package' => 'rep_recapitulation',
    'name' => 'rep_recapitulation',
    'version' => '-',
    'available' => '',
    'type' => 'extension',
    'path' => 'modules/rep_recapitulation',
    'active' => 1,
  ),
);
?>